### ISSUE TITLE
Not working on iOS 12.1 using uncover jailbreak.

### ISSUE THREAD

**Issue by alexdominat** [Muirey03/Cr4shed#3]

**Comment by Kunderscore** [comment]
works for me

**Comment by Muirey03** [comment]
Fixed in 2.0

**Comment by alexdominat** [comment]
still not working. Im crashing sb using ultrasounds oled mode in ios 12. No
logs show up in the app

Στις Παρ, 1 Μαρ 2019 στις 8:48 μ.μ., ο/η Tommy Muir <
notifications@github.com> έγραψε:
